name: bouzu_repeat
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.8
  go_router: ^13.0.0
  table_calendar: ^3.2.0
  share_plus: ^7.2.1
  google_mobile_ads: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bouzu_lv1.png
    - assets/images/bouzu_lv2.png
